language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: RgrAS1mH3QGysPhkxDSPQUU4c1o4X7E/VlWtXpMbfkYSjYZCoE4ZOeam6lQjLOEpgpo4jAvCTN5umMFs0cJh3aUvwLFZzN0PA5YiR4Lb0SVTDGC1bRs7ygHneURsVD9mboW5GdDnR6xIhFPr3yhTK/SWHvqCU7KFVFsIIW7wz8bVMzCvLHmFX2M0rAxZduyzGna9vuqC7asxyqJBFHFThucfU95yFKA3T7t2UUtqIuoKkCRYfEMPdNanjg7KqiBl3vIfgLpr2rNjYI3/yzavouXlWDgQJIDqqPX85p+hv314qZ0Z4hYRsBiea4ttl7UTA59QTmLgT8Nk0DfFMs39lh08bnp8Hgra0lsA4g0qUsLM9GT8pV4uEsMd9EZgxF94yRbIP18qhrLhUvk1kJ3mPUxZVpOQ83jeJiItf1srjfcqRniiMNv5/xe4Q7vE6flcg/q2wMra0YhJQ3JGZgoizAey1+PpatC24Kaa1cpdbYWncY43tsrEaPaEhq8077TA8qjjRNuBuQjPyODfqlBzizKo4S8DhkPL2JUJ7qPRlD2YLLD1VYkNLbw1nt3BOGMIwwv9ZWEy0RoFdazTEC4ewVeY/beKkKn1ZJTqDcegybdBajQKHEUpCfObgK9hcGgVTjECtStCY65E2N1vYE6e1iD1zvwK/mQAFGt+EGMhW4E=
